name: 'Publish Package'
description: 'Bump up package version and publish to npm'
inputs:
  package_name:
    required: true
    type: string
  package_path:
    required: true
    type: string
  npm_token:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Bump up version for ${{ inputs.package_name }}
      run: npm run bump:${{ inputs.package_name }}
      shell: bash

    # TODO: npm adduser login
    - name: Publish package ${{ inputs.package_name }} to NPM
      shell: bash
      run: npm run publish:${{ inputs.package_name }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
