name: 'Build Package'
description: 'Build a Library Package'
inputs:
  package_name:
    required: true
    type: string
  package_path:
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Clean install dependencies and build in package ${{ inputs.package_name }}
      working-directory: ${{ inputs.package_path }}
      run: |
        npm ci
        npm run build
      shell: bash
