name: Reusable workflow example

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      package_path:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Get Diff
        id: get-diff
        run: |
          npm run diff:${{ inputs.package_name }} || echo "::set-output name=hasChange::true"
      - name: Clean install dependencies and build in package ${{ inputs.package_name }}
        working-directory: ${{ inputs.package_path }}
        if: '${{ steps.get-diff.outputs.hasChange }}'
        run: |
          npm ci
          npm run build
          npm test
