name: Package Release Pipeline

# on:
#   release:
#     types: [created]

# on:
#   pull_request:
#     branches: ['master']

on:
  workflow_dispatch:

jobs:
  build_a:
    name: Build Package A
    uses: ./.github/workflows/build-package.yml
    with:
      package_name: a
      package_path: ./packages/a

  build_b:
    needs: build_a
    name: Build Package B
    uses: ./.github/workflows/build-package.yml
    with:
      package_name: b
      package_path: ./packages/b

  publish-npm:
    needs: [build_a, build_b]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./packages/a
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./packages/b
      - run: npm version patch -w a
      - run: git add .
      - run: git commit -m "Upgrade for ci [skip ci]"
      - name: 'Push version to package.json'
        run: git push origin HEAD:refs/heads/master -f
