name: Package PR Pipeline

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Clean install dependencies and build in package a
        working-directory: ./packages/a
        run: |
          npm ci
          npm run build
          npm test
      - name: Clean install dependencies and build in package b
        working-directory: ./packages/b
        run: |
          npm ci
          npm run build
          npm test
