# name: Package PR Pipeline

# on:
#   pull_request:
#     branches: ['master']

# jobs:
#   build_a:
#     name: Build Package A
#     uses: ./.github/workflows/build-package.yml
#     with:
#       package_name: a
#       package_path: ./packages/a
#   build_b:
#     needs: build_a
#     name: Build Package B
#     uses: ./.github/workflows/build-package.yml
#     with:
#       package_name: b
#       package_path: ./packages/b
