name: Release Pipeline using Composite Action Templates

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Get Diff
        id: get-diff
        run: |
          npm run diff:a || echo "::set-output name=hasAChange::true"
          npm run diff:b || echo "::set-output name=hasBChange::true"
      - name: Run CI for Package A
        if: ${{ steps.get-diff.outputs.hasAChange }}
        id: ci_a
        ## Use github composite action defined in the `actions` folder
        ## This template allows us to create reusable steps that can be nested in the same job
        uses: ./actions/full-ci
        with:
          package_name: a
          package_path: ./packages/a
      - name: Build Package A
        if: ${{ !steps.get-diff.outputs.hasAChange && steps.get-diff.outputs.hasBChange }}
        id: build_a
        uses: ./actions/build-package
        with:
          package_name: a
          package_path: ./packages/a
      - name: Run CI for Package B
        if: ${{ steps.get-diff.outputs.hasBChange }}
        id: ci_b
        uses: ./actions/full-ci
        with:
          package_name: b
          package_path: ./packages/b
