name: Release Pipeline using Composite Action Templates

# on:
#   push:
#     branches:
#       - master

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up NodeJS 16 and .npmrc
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
          # Defaults to the user or organization that owns the workflow file
          scope: '@stephaniez_rangle'
      - name: Get Diff
        id: get-diff
        run: |
          npm run diff:a || echo "::set-output name=hasAChange::true"
          npm run diff:b || echo "::set-output name=hasBChange::true"
      - name: Run CI for Package A
        # if: ${{ steps.get-diff.outputs.hasAChange }}
        id: ci_a
        ## Use github composite action defined in the `actions` folder
        ## This template allows us to create reusable steps that can be nested in the same job
        uses: ./actions/full-ci
        with:
          package_name: a
          package_path: ./packages/a
      - name: Build Package A
        if: ${{ !steps.get-diff.outputs.hasAChange && steps.get-diff.outputs.hasBChange }}
        id: build_a
        uses: ./actions/build-package
        with:
          package_name: a
          package_path: ./packages/a
      - name: Run CI for Package B
        # if: ${{ steps.get-diff.outputs.hasBChange }}
        id: ci_b
        uses: ./actions/full-ci
        with:
          package_name: b
          package_path: ./packages/b
      - name: Publish Package A
        # if: ${{ steps.get-diff.outputs.hasAChange }}
        uses: ./actions/release-package
        with:
          package_name: a
          package_path: ./packages/a
          npm_token: ${{ secrets.NPM_PUBLISH_PACKAGE_TOKEN }}
      - name: Publish Package B
        # if: ${{ steps.get-diff.outputs.hasBChange }}
        uses: ./actions/release-package
        with:
          package_name: b
          package_path: ./packages/b
          npm_token: ${{ secrets.NPM_PUBLISH_PACKAGE_TOKEN }}
      ## Compare master and the last release tag git diff
      - name: Push version changes to git repo
        # if: ${{ steps.get-diff.outputs.hasAChange || steps.get-diff.outputs.hasBChange }}
        run: |
          git config user.email "stephanie.zeng@rangle.io"
          git config user.name "Stephanie Zeng"
          git add .
          git commit -m "Update package versions [skip ci]"
          git fetch origin master
          git push origin HEAD:master
